### ISSUE TITLE
It's not a problem, just a way to reach you

### ISSUE THREAD

**Issue by baalp** [turboboy215/MET22MID#1]
Hi. I am doing a project and I would like to get mid soundtrack files from Pokemon Red. You don't have such a converter yet. I would be very happy if you make one, thanks for your attention

**Comment by turboboy215** [comment]
I will work on Game Freak's driver soon. Right now, I am working on RARE's sound driver (DKL etc.), which is a pain to work on due to the set of commands differing from game to game (some are the same, though).
This should be much more straightforward to do, especially since all the Pokémon games have been disassembled.

**Comment by turboboy215** [comment]
Here is the program: https://github.com/turboboy215/GF2MID
